# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.15.12@sha256:d9b939055c1e852fe3d86955ee24976cab46cba518abcb8b13ba70917e6547a6
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 31380
        hostPort: 80
        protocol: TCP
      - containerPort: 31390
        hostPort: 443
        protocol: TCP
      - containerPort: 15012
        hostPort: 15012
        protocol: TCP
      - containerPort: 30870
        hostPort: 81
        protocol: TCP
  - role: worker
    image: kindest/node:v1.15.12@sha256:d9b939055c1e852fe3d86955ee24976cab46cba518abcb8b13ba70917e6547a6
